inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.1
  TargetRailsVersion: 6.1
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/bundle/**/*"
    - "bin/**/*"

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/Documentation:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

# Error occured while Rails/UniqueValidationWithoutIndex cop was inspecting files which is not handled
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true
  IndentOneStep: true
  IndentationWidth: 2

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - prepend
      - include
      - extend
    default_scope:
      - default_scope
    accepts_nested_attributes:
      - accepts_nested_attributes
    belongs_to_associations: -belongs_to
    has_one_associations: -has_one
    has_many_associations: -has_many
    has_and_belongs_to_many_associations: -has_and_belongs_to_many
    validations:
      - validates
    scopes: -scope
  ExpectedOrder:
    - default_scope
    - module_inclusion
    - constants
    - accepts_nested_attributes
    - belongs_to_associations
    - has_one_associations
    - has_many_associations
    - has_and_belongs_to_many_associations
    - validations
    - scopes
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: "symmetrical"

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: "same_line"

# Layout/MultilineBlockLayout:
#   Enabled: true

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "config/environments/**/*"
    - "app/services/dnar_transaction_service.rb"
    - "**/*_spec.rb"
    - "lib/tasks/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - "db/seeds.rb"

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: "symmetrical"

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: "symmetrical"

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
  EnforcedStyle: "symmetrical"

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: "aligned"

Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: "require_space"

Layout/LineLength:
  Enabled: true
  Max: 120
  Include:
    - "app/controllers/**/*"
    - "app/helpers/**/*"
    - "app/models/**/*"
  Exclude:
    - "**/*_spec.rb"
    - "lib/tasks/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Enabled: true
  Exclude:
    - "db/seeds.rb"

Rails/TimeZone:
  Enabled: true
  Exclude:
    - "db/seeds.rb"

Style/ExpandPathArguments:
  Enabled: true
  Exclude:
    - "config/**/**"
    - "test/**/**"

Lint/EmptyBlock:
  Exclude:
    - "lib/tasks/**/**"

Style/ImplicitRuntimeError:
  Enabled: true
  Exclude:
    - "lib/tasks/**"

Style/Lambda:
  Enabled: true
  EnforcedStyle: "literal"

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - "config.ru"
    - "db/migrate/**"
    - "db/seeds.rb"
    - "config/**/**"
    - "Gemfile"

  AllowedMethods:
    [
      "require",
      "raise",
      "authorize",
      "require_relative",
      "render",
      "rescue_from",
      "throw",
      "mail",
      "yield",
      "puts",
    ]

Style/PercentLiteralDelimiters:
  Enabled: true
  Exclude:
    - "config/**/**"

# Style/RedundantSelf:
#   Enabled: true

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: "mixed"
  AllowInnerSlashes: true

Style/RescueModifier:
  Enabled: true
  Exclude:
    - "config/**/**"
    - "lib/tasks/migration.rake"

Style/Semicolon:
  Enabled: true
  Exclude:
    - "db/seeds.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Rails/WhereNotWithMultipleConditions:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - "**/*_spec.rb"
