# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i + 5 %>

development:
  <<: *default
  database: dev_ops_development
  username: 'postgres'
  password: '1234'

test:
  <<: *default
  database: dev_ops_test
  username: 'postgres'
  password: '1234'

production:
  <<: *default
  database: dev_ops_production
  username: 'postgres'
  password: '1234'
  host: <%= Rails.application.credentials.DATABASE_HOST %>
  port: <%= Rails.application.credentials.DATABASE_PORT %>
