env:
  RUBY_VERSION: 3.2.2
  RAILS_ENV: test
  DATABASE_HOST: localhost
  DATABASE_URL:  postgres://postgres:postgres@localhost
  DATABASE_NAME: dev_ops_test
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
name: Rails Workflows
on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches: [ "main" ]
jobs:
  rubo-cop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec brakeman

